// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA30KhJw3dCPFfxvdvo5g3N_aH8opleRwk',
    appId: '1:982326544628:web:84fb8303243785ccbbf6a1',
    messagingSenderId: '982326544628',
    projectId: 'classcare-a90a6',
    authDomain: 'classcare-a90a6.firebaseapp.com',
    storageBucket: 'classcare-a90a6.firebasestorage.app',
    measurementId: 'G-3RXFV38KTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPNdXMs_XWi4eaHjTqa0vmq1sr130jj9Y',
    appId: '1:982326544628:android:d74225b090ec5968bbf6a1',
    messagingSenderId: '982326544628',
    projectId: 'classcare-a90a6',
    storageBucket: 'classcare-a90a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLhhBKlq11SeTarUtLHvwp3pilletel_8',
    appId: '1:982326544628:ios:923b948a2e5e681dbbf6a1',
    messagingSenderId: '982326544628',
    projectId: 'classcare-a90a6',
    storageBucket: 'classcare-a90a6.firebasestorage.app',
    iosBundleId: 'com.example.classcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLhhBKlq11SeTarUtLHvwp3pilletel_8',
    appId: '1:982326544628:ios:923b948a2e5e681dbbf6a1',
    messagingSenderId: '982326544628',
    projectId: 'classcare-a90a6',
    storageBucket: 'classcare-a90a6.firebasestorage.app',
    iosBundleId: 'com.example.classcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA30KhJw3dCPFfxvdvo5g3N_aH8opleRwk',
    appId: '1:982326544628:web:2b6fa7b3a7aecd98bbf6a1',
    messagingSenderId: '982326544628',
    projectId: 'classcare-a90a6',
    authDomain: 'classcare-a90a6.firebaseapp.com',
    storageBucket: 'classcare-a90a6.firebasestorage.app',
    measurementId: 'G-N0JGHETHJ1',
  );
}
